services:
  - type: web
    name: khedim-ia-anp
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: GROQ_API_KEY_1
        sync: false
      - key: GROQ_API_KEY_2
        sync: false
      - key: GROQ_API_KEY_3
        sync: false
      - key: PORT
        value: 10000
